<?php

return [
    [
        'id' => '88fm-sede',
        'name' => 'Radio 88 FM - SEDE',
        'station' => 'Radio 88 FM',
        'city' => 'Volta Redonda',
        'state' => 'RJ',
        'frequency' => '88,7 MHz',
        'provider' => 'Srvstm',
        'protocol' => 'HTTP Audio',
        'stream_url' => 'https://stm39.srvstm.com:9776/stream',
        'fallback_url' => null,
        'metadata_url' => null,
        'stats_url' => null,
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-bh',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - SEDE',
        'city' => 'Belo Horizonte',
        'state' => 'MG',
        'frequency' => '89,1 MHz',
        'provider' => 'Srvstm',
        'protocol' => 'HTTP Audio',
        'stream_url' => 'https://stm19.srvstm.com:7080/stream',
        'fallback_url' => null,
        'metadata_url' => null,
        'stats_url' => null,
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-cambui',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Cambui',
        'state' => 'MG',
        'frequency' => '98,9 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv2.soundstream.com.br/listen/maravilhafmcambui/live',
        'fallback_url' => 'http://srv2.soundstream.com.br:8040/live',
        'metadata_url' => 'https://srv2.soundstream.com.br/api/nowplaying/maravilhafmcambui',
        'stats_url' => 'http://srv2.soundstream.com.br:8040/status-json.xsl',
        'metadata_offline_means_down' => true,
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-barbacena',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Barbacena',
        'state' => 'MG',
        'frequency' => '89,3 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv2.soundstream.com.br/listen/maravilhafmbarbacena/live',
        'fallback_url' => 'http://srv2.soundstream.com.br:8020/live',
        'metadata_url' => 'https://srv2.soundstream.com.br/api/nowplaying/maravilhafmbarbacena',
        'stats_url' => 'http://srv2.soundstream.com.br:8020/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-ipatinga',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Ipatinga',
        'state' => 'MG',
        'frequency' => '89,5 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv2.soundstream.com.br/listen/maravilhafmipatinga/live',
        'fallback_url' => 'http://srv2.soundstream.com.br:8030/live',
        'metadata_url' => 'https://srv2.soundstream.com.br/api/nowplaying/maravilhafmipatinga',
        'stats_url' => 'http://srv2.soundstream.com.br:8030/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-campos-gerais',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Campos Gerais',
        'state' => 'MG',
        'frequency' => '97,1 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhacamposgerais/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8170/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhacamposgerais',
        'stats_url' => 'http://srv.soundstream.com.br:8170/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-joao-pinheiro',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Joao Pinheiro',
        'state' => 'MG',
        'frequency' => '94,7 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhafm/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8180/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhafm',
        'stats_url' => 'http://srv.soundstream.com.br:8180/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-juiz-de-fora',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Juiz de Fora',
        'state' => 'MG',
        'frequency' => '89,7 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br:8030/live',
        'fallback_url' => null,
        'metadata_url' => null,
        'stats_url' => 'https://srv.soundstream.com.br:8030/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-leopoldina',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Leopoldina',
        'state' => 'MG',
        'frequency' => '89,1 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhafmleopoldina/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8270/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhafmleopoldina',
        'stats_url' => 'http://srv.soundstream.com.br:8270/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-montes-claros',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Montes Claros',
        'state' => 'MG',
        'frequency' => '89,5 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhafmmontesclaros/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8020/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhafmmontesclaros',
        'stats_url' => 'http://srv.soundstream.com.br:8020/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-teofilo-otoni',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Teofilo Otoni',
        'state' => 'MG',
        'frequency' => '87,7 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhateofilootoni/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8240/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhateofilootoni',
        'stats_url' => 'http://srv.soundstream.com.br:8240/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-uba',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Uba',
        'state' => 'MG',
        'frequency' => '89,9 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhafmuba/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8040/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhafmuba',
        'stats_url' => 'http://srv.soundstream.com.br:8040/status-json.xsl',
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-uberaba',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Uberaba',
        'state' => 'MG',
        'frequency' => '89,3 MHz',
        'provider' => 'Srvstm',
        'protocol' => 'HTTP Audio',
        'stream_url' => 'https://stm6.srvstm.com:7006/stream',
        'fallback_url' => null,
        'metadata_url' => null,
        'stats_url' => null,
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-uberlandia',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Uberlandia',
        'state' => 'MG',
        'frequency' => '89,7 MHz',
        'provider' => 'Srvstm',
        'protocol' => 'HTTP Audio',
        'stream_url' => 'https://stm6.srvstm.com:7076/stream',
        'fallback_url' => null,
        'metadata_url' => null,
        'stats_url' => null,
        'control_mode' => 'observador',
    ],
    [
        'id' => 'maravilha-araxa',
        'name' => 'Radio Maravilha FM',
        'station' => 'Maravilha FM - Afiliada',
        'city' => 'Araxa',
        'state' => 'MG',
        'frequency' => '91,5 MHz',
        'provider' => 'Soundstream',
        'protocol' => 'Icecast2',
        'stream_url' => 'https://srv.soundstream.com.br/listen/maravilhafmaraxa/live',
        'fallback_url' => 'http://srv.soundstream.com.br:8290/live',
        'metadata_url' => 'https://srv.soundstream.com.br/api/nowplaying/maravilhafmaraxa',
        'stats_url' => 'http://srv.soundstream.com.br:8290/status-json.xsl',
        'control_mode' => 'observador',
    ],
];
